### ISSUE TITLE
No shield named 'mr_canhubk3_adap' found

### ISSUE THREAD

**Issue by zzx0226** [CogniPilot/cerebri#125]
Hi Guys,

I am trying to compile the FW for mr_canhubk3, by using command "west build -b mr_canhubk3 cerebri/app/b3rb -p", but error occured.

It said "No shield named 'mr_canhubk3_adap' found".

log:
-- west build: making build dir /home/zzx/zephyr/build pristine
-- west build: generating a build system
-- enabling mr_canhubk3_adap shield
Loading Zephyr default modules (Zephyr base).
-- Application: /home/zzx/zephyr/cerebri/app/b3rb
-- CMake version: 3.28.2
-- Found Python3: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/zzx/.cache/zephyr
-- Zephyr version: 3.5.99 (/home/zzx/zephyr/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: mr_canhubk3
-- Shield(s): mr_canhubk3_adap
No shield named 'mr_canhubk3_adap' found
Please choose from among the following shields:
adafruit_2_8_tft_touch_v2
adafruit_2_8_tft_touch_v2_nano
.....

I also didn't find the information for "mr_canhubk3_adap" in the Zephyr/boards/shields folder. Please help me on this.

Thanks for your help!

BR,
Zixu

**Comment by bperseghetti** [comment]
Hi @zzx0226 please make sure to use the west.yaml in cerebri as your manifest for cloning/updating zephyr. We suggest everyone follows the install method on https://airy.cognipilot.org/getting_started/install/

**Comment by bperseghetti** [comment]
Since we had worked on this through direct messaging I'm marking it as done/resolved.
